#!/usr/bin/env node
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function getGitInfo() {
  try {
    const commitCount = execSync('git rev-list --count HEAD', { encoding: 'utf-8' }).trim();
    const shortHash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
    return { commitCount, shortHash };
  } catch {
    console.warn('Warning: Could not read git info. Using defaults.');
    return { commitCount: '0', shortHash: 'unknown' };
  }
}

const { commitCount, shortHash } = getGitInfo();
const version = `0.0.${commitCount}`;
const display = `v${version} (${shortHash})`;

const content = `// Auto-generated by generate-version.js — do not edit manually
var APP_VERSION = ${JSON.stringify(version)};
var APP_VERSION_DISPLAY = ${JSON.stringify(display)};
var APP_COMMIT_HASH = ${JSON.stringify(shortHash)};
var APP_COMMIT_HEIGHT = ${JSON.stringify(commitCount)};
`;

const outPath = path.join(__dirname, 'version.js');
fs.writeFileSync(outPath, content, 'utf-8');
console.log(`Generated version.js: ${display}`);
